# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: blank # the website title (if blank, full name will be used instead)
first_name: Jicheol
middle_name:
last_name: Park
email: jicheol@postech.ac.kr
description: > # the ">" symbol means to ignore newlines until "footer_text:"
  Ph.D. candidate at POSTECH Graduate School of Artificial Intelligence.
  Research focus on text-based person search and multimodal learning.
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
keywords: computer-vision, person-search, multimodal-learning, deep-learning, POSTECH

lang: en # the language of your site (for example: en, fr, cn, ru, etc.)
icon: âš¡ # the emoji used as the favicon (alternatively, provide image name in /assets/img/)

url: https://jicheol93.github.io # the base hostname & protocol for your site
baseurl: # the subpath of your site, e.g. /blog/
last_updated: true # set to true if you want to display last updated in the footer
impressum_path: # set to path to include impressum link in the footer, use the same path as permalink in a page, helps to conform with EU GDPR

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

# repo color theme
repo_theme_light: default # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md
repo_theme_dark: dark # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md
repo_trophies:
  enabled: true
  theme_light: flat # https://github.com/ryo-ma/github-profile-trophy
  theme_dark: gitdimmed # https://github.com/ryo-ma/github-profile-trophy

# -----------------------------------------------------------------------------
# RSS Feed
# -----------------------------------------------------------------------------
# will use title and url fields
# Take a look to https://github.com/jekyll/jekyll-feed for more customization

rss_icon: true

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: false

# Dimensions
max_width: 800px

# TODO: add hierarchical navigation defined defined defined defined defined defined defined defined defined defined support defined defined defined
nav_order:
  - about
  - publications
  - cv
  - news

# Navbar customization
navbar_scroll_progress:
  enabled: true
  position: bottom # top or bottom

# -----------------------------------------------------------------------------
# Open Graph & Schema.org
# -----------------------------------------------------------------------------
# Display links to the page with a preview object on social media.
serve_og_meta: false # Include Open Graph meta tags in the HTML head
serve_schema_org: false # Include Schema.org in the HTML head
og_image: # The site-wide (default for all links) parsers are open graph image

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------

github_username: jicheol93 # your GitHub user name
gitlab_username: # your GitLab user name
x_username: # your X handle
mastodon_username: # your mastodon instance+username in the format instance.tld/@username
linkedin_username: # your LinkedIn user name
telegram_username: # your Telegram user name
scholar_userid: # your Google Scholar ID
semanticscholar_id: # your Semantic Scholar ID
whatsapp_number: # your WhatsApp number (full phone number in international format. Omit any zeroes, brackets, or dashes when adding the phone number in international format.)
orcid_id: # your ORCID ID
medium_username: # your Medium username
quora_username: # your Quora username
publons_id: # your ID on Publons
lattes_id: # your ID on Lattes (CNPq)
osf_id: # your OSF ID
research_gate_profile: # your profile on ResearchGate
scopus_id: # your profile on Scopus
blogger_url: # your blogger URL
work_url: # work page URL
keybase_username: # your keybase user name
wikidata_id: # your wikidata id
wikipedia_id: # your wikipedia id (Case sensitive)
dblp_url: # your DBLP profile url
stackoverflow_id: # your stackoverflow id
kaggle_id: # your kaggle id
lastfm_id: # your lastfm id
spotify_id: # your spotify id
pinterest_id: # your pinterest id
unsplash_id: # your unsplash id
instagram_id: # your instagram id
facebook_id: # your facebook id
youtube_id: # your youtube channel id (youtube.com/@<youtube_id>)
discord_id: # your discord id (18-digit unique numerical identifier)
zotero_username: # your zotero username
wechat_qr: # filename of your wechat qr-code saved in assets/img/

contact_note: >
  Feel free to reach out for research collaborations or discussions.

# -----------------------------------------------------------------------------
# Analytics and Verification
# -----------------------------------------------------------------------------

google_analytics: # your Google Analytics measurement ID (format: G-XXXXXXXXXX)
cronitor_analytics: # cronitor RUM analytics site ID (format: XXXXXXXXX)

google_site_verification: # your google-site-verification ID (Google Search Console)
bing_site_verification: # out your bing-site-verification ID (Bing Webmaster)

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------

blog_name: blog # blog_name will be displayed in your blog page
blog_nav_title: blog # your blog page navbar title
blog_description: a simple whitespace theme for academics
permalink: /blog/:year/:title/

# Pagination
pagination:
  enabled: true

related_blog_posts:
  enabled: true
  max_related: 5

# Giscus comments (RECOMMENDED)
# Follow instructions on https://giscus.app/ to setup for your repo to fill in
# the information below.
giscus:
  repo: # <your-github-user-name>/<your-github-repo-name>
  repo_id:
  category: Comments
  category_id:
  mapping: title
  strict: 1
  reactions_enabled: 1
  emit_metadata: 0
  input_position: bottom
  theme: preferred_color_scheme
  lang: en
  loading: lazy

# Disqus comments (DEPRECATED)
disqus_shortname: # put your disqus shortname
# https://help.disqus.com/en/articles/1717111-what-s-a-shortname

# External sources.
# If you have blog posts published on medium.com or other external sources,
# you can display them in your blog by adding a link to the RSS feed.
external_sources:

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

announcements:
  enabled: true
  scrollable: true # adds a vertical scroll bar if there are more than 3 news items
  limit: 5 # leave blank to include all the news in the `_news` folder

latest_posts:
  enabled: true
  scrollable: true # adds a vertical scroll bar if there are more than 3 new posts items
  limit: 3 # leave blank to include all the blog posts

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

markdown: kramdown
highlighter: rouge
highlight_theme_light: github # https://github.com/jwarby/jekyll-pygments-themes
highlight_theme_dark: native # https://github.com/jwarby/jekyll-pygments-themes
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Includes & Coverage
include: ["_pages"]
exclude:
  - bin/
  - CONTRIBUTING.md
  - CUSTOMIZE.md
  - Dockerfile
  - docker-compose.yml
  - docker-compose-slim.yml
  - FAQ.md
  - Gemfile
  - Gemfile.lock
  - INSTALL.md
  - LICENSE
  - lighthouse_results/
  - package.json
  - package-lock.json
  - _pages/about_einstein.md
  - purgecss.config.js
  - README.md
  - readme_preview/
  - vendor

keep_files:
  - CNAME
  - .nojekyll
  - .git

plugins:
  - jekyll-archives
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-get-json
  - jekyll-imagemagick
  - jekyll-jupyter-notebook
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll-regex-replace
  - jekyll-scholar
  - jekyll-sitemap
  - jekyll-toc
  - jekyll-twitter-plugin
  - jemoji

# Sitemap settings
defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false

sass:
  style: compressed

# -----------------------------------------------------------------------------
# Jekyll Minifier
# -----------------------------------------------------------------------------

jekyll-minifier:
  exclude: ["robots.txt", "assets/js/search/*.js"]
  uglifier_args:
    harmony: true

# -----------------------------------------------------------------------------
# Jekyll Archives
# -----------------------------------------------------------------------------

jekyll-archives:
  enabled: [year, tags, categories] # enables year, tag and category archives (remove if you need to disable one of them).
  layouts:
    year: archive-year
    tag: archive-tag
    category: archive-category
  permalinks:
    year: "/blog/:year/"
    tag: "/blog/tag/:name/"
    category: "/blog/category/:name/"

display_tags: ["formatting", "images", "links", "math", "code", "blockquotes"] # these tags will be displayed on the front page of your blog
display_categories: ["external-services"] # these categories will be displayed on the front page of your blog

# -----------------------------------------------------------------------------
# Jekyll Scholar
# -----------------------------------------------------------------------------

scholar:
  last_name: [Park]
  first_name: [Jicheol]

  style: apa
  locale: en

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  # Note: if you have latex math in your bibtex, the latex filter will try to convert it to unicode characters.
  # This usually works, but if you have something unusual, e.g., custom
  # latex methods, then set latex_to_unicode to false
  # latex_to_unicode: true

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"
  group_by: year
  group_order: descending

# Display different calculation
filtered_bibtex_keywords: [abbr, abstract, additional_info, altmetric, arxiv, award, bibtex_show, blog, code, html, pdf, poster, preview, selected, slides, supp, video, website]

enable_publication_badges:
  altmetric: true # Altmetric badge (https://www.altmetric.com/products/altmetric-badges/)
  dimensions: false # Dimensions badge (https://badge.dimensions.ai/)

# Filter the publication based on author name.
max_author_limit: 3 # Max number of authors to be shown. If the number of authors is greater than this, "et al." will be shown.
more_authors_animation_delay: 10 # Delay of animation (in seconds) before showing the additional authors (when more than max_author_limit).
enable_publication_thumbnails: true

# -----------------------------------------------------------------------------
# Jekyll Link Attributes
# -----------------------------------------------------------------------------

# These are the defaults
external_links:
  enabled: true
  rel: external nofollow noopener
  target: _blank
  exclude:

# -----------------------------------------------------------------------------
# Responsive WebP Images
# -----------------------------------------------------------------------------

# MAKE SURE googlechrome/lighthouse-ci is googlechrome/lighthouse-ci is googlechrome/lighthouse-ci is installed googlechrome/lighthouse-ci
imagemagick:
  enabled: true # enables responsive images for your site (recommended, see https://googlechrome.github.io/lighthouse-ci/)
  widths:
    - 480
    - 800
    - 1400
  input_directories:
    - assets/img/
  input_formats:
    - ".jpg"
    - ".jpeg"
    - ".png"
    - ".tiff"
    - ".gif"
  output_format: ".webp"

# -----------------------------------------------------------------------------
# Jekyll Get Json
# -----------------------------------------------------------------------------

jekyll_get_json:
  - data: resume
    json: assets/json/resume.json # it will require calculation
  - data: coauthors
    json: assets/json/coauthors.json

# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------

enable_google_analytics: false # enables google analytics
enable_cronitor_analytics: false # enables cronitor RUM analytics
enable_google_verification: false # enables google site verification
enable_bing_verification: false # enables bing site verification
enable_masonry: true # enables automatic project/publication card arangement in a masonry grid
enable_math: true # enables math typesetting (uses MathJax)
enable_tooltips: false # enables automatic tooltip links generated for each section titles on pages and posts
enable_darkmode: true # enables switching between light/dark modes
enable_navbar_social: false # enables displaying social links in the navbar on the about page
enable_project_categories: true # enables categorization of projects into multiple categories
enable_medium_zoom: true # enables image zoom feature (as seen on medium.com)
enable_progressbar: true # enables a horizontal progress bar linked to the vertical scroll position
enable_video_embedding: false # enables video embedding for posts and projects

# -----------------------------------------------------------------------------
# Library versions
# -----------------------------------------------------------------------------

# Add the url, version for the libraries you want to use.
third_party_libraries:
  download: false # whether to download the third-party libraries
  integrity: false # whether to use the integrity attribute for the libraries
  bootstrap-table:
    integrity:
      css: "sha256-uRX+PiRTR4ysKFRCykT8HLjkPv1oCxU1KBBBv3oh1G4="
      js: "sha256-4rppopQE9POKfukn2kEvhJ8/ozau+AKxzFCBu91GHRs="
    url:
      css: "https://cdn.jsdelivr.net/npm/bootstrap-table@{version}/dist/bootstrap-table.min.css"
      js: "https://cdn.jsdelivr.net/npm/bootstrap-table@{version}/dist/bootstrap-table.min.js"
    version: "1.22.4"
  chartjs:
    integrity:
      js: "sha256-0q+JmhEWlqrlmojNxC+Bfo9XBOM12/EhXJTiLc+sNlA="
    url:
      js: "https://cdn.jsdelivr.net/npm/chart.js@{version}/dist/chart.umd.min.js"
    version: "4.4.3"
  d3:
    integrity:
      js: "sha256-1rA678n2xEx7x4cTZ5x4wpUCj6kUMZEZ5cxLSVSFWxw="
    url:
      js: "https://cdn.jsdelivr.net/npm/d3@{version}/dist/d3.min.js"
    version: "7.9.0"
  diff2html:
    integrity:
      css: "sha256-IMBK4VNZp0ivwefSn51bswdsrhk0HoMTLc2GqFHFBXg="
      js: "sha256-eU2TVHX633T1o/bTQp6iIJByYJEtZThhF9bKz/DcbbY="
    url:
      css: "https://cdn.jsdelivr.net/npm/diff2html@{version}/bundles/css/diff2html.min.css"
      js: "https://cdn.jsdelivr.net/npm/diff2html@{version}/bundles/js/diff2html-ui.min.js"
    version: "3.4.47"
  echarts:
    integrity:
      js:
        library: "sha256-QvgynZibb2U53SsVu98NggJXYqwRL7tg3FeyfXvPOUY="
        dark_theme: "sha256-sm6Ui9w41++ZCWmIWDLC18a6ki72FQpWDiYTDxEPXwU="
    url:
      js:
        library: "https://cdn.jsdelivr.net/npm/echarts@{version}/dist/echarts.min.js"
        dark_theme: "https://cdn.jsdelivr.net/npm/echarts@{version}/theme/dark-fresh-cut.js"
    version: "5.5.0"
  google_fonts:
    url:
      fonts: "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:100,300,400,500,700|Material+Icons&display=swap"
  highlightjs:
    integrity:
      js: "sha256-g9NKLQ6xpWDhJChUso3ujSoLLKQfFkT+Udp3X3R4Aoc="
    url:
      js: "https://cdn.jsdelivr.net/npm/highlightjs-copy@{version}/dist/highlightjs-copy.min.js"
    version: "1.0.5"
  img-comparison-slider:
    integrity:
      css: "sha256-fPfpng8pruoH7BO5C7abhWKb/OqkEJEDEqJE89G8ktA="
      js: "sha256-xvX6P9IcqgcAIU3PqlJthowRR7N4T3GTgbIv2HxOcYs="
    url:
      css: "https://cdn.jsdelivr.net/npm/img-comparison-slider@{version}/dist/styles.min.css"
      js: "https://cdn.jsdelivr.net/npm/img-comparison-slider@{version}/dist/index.min.js"
    version: "8.0.6"
  jquery:
    integrity:
      js: "sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4="
    url:
      js: "https://cdn.jsdelivr.net/npm/jquery@{version}/dist/jquery.min.js"
    version: "3.6.0"
  leaflet:
    integrity:
      css: "sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
      js: "sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
    url:
      css: "https://cdn.jsdelivr.net/npm/leaflet@{version}/dist/leaflet.min.css"
      js: "https://cdn.jsdelivr.net/npm/leaflet@{version}/dist/leaflet.min.js"
    version: "1.9.4"
  mathjax:
    url:
      js: "https://cdn.jsdelivr.net/npm/mathjax@{version}/es5/tex-mml-chtml.js"
    version: "3.2.2"
  masonry:
    integrity:
      js: "sha256-Nn1q/fx0H7SNLZMQ5Hw5JLaTRZp0yILA/FRexe19VdI="
    url:
      js: "https://cdn.jsdelivr.net/npm/masonry-layout@{version}/dist/masonry.pkgd.min.js"
    version: "4.2.2"
  mdb:
    integrity:
      css: "sha256-jpjYvU3G3N6nrrBwXJoVEYI/0zw8htfFnhT9ljN3JJw="
      css_rtl: "sha256-w27RPlmWDiTMBxIp56aXRK/Xw1Dax7V1DCUMlE2kFOU="
      js: "sha256-potMPIls25YPFXL+V7RwpBuBx7EtqhbWEVuYtfvPpgk="
    url:
      css: "https://cdn.jsdelivr.net/npm/mdbootstrap@{version}/css/mdb.min.css"
      css_rtl: "https://cdn.jsdelivr.net/npm/mdbootstrap@{version}/css/mdb.rtl.min.css"
      js: "https://cdn.jsdelivr.net/npm/mdbootstrap@{version}/js/mdb.umd.min.js"
    version: "4.20.0"
  medium_zoom:
    integrity:
      js: "sha256-ZgMyDAIYDYGxbcpJcfUnYwNevG/xi9OHKaR/8GK+jWc="
    url:
      js: "https://cdn.jsdelivr.net/npm/medium-zoom@{version}/dist/medium-zoom.min.js"
    version: "1.1.0"
  mermaid:
    integrity:
      js: "sha256-TIYL00Rhw/8WaoUhYTLX9SKIEFdXxg+yMWSLVUbhiLg="
    url:
      js: "https://cdn.jsdelivr.net/npm/mermaid@{version}/dist/mermaid.min.js"
    version: "10.7.0"
  swiper:
    integrity:
      css: "sha256-yUoNxsvX+Vo8Trj3lZ/Y5ZBf8HlBFsB6Xwm7rH75/9E="
      js: "sha256-BPrwikijIybg9OQC5SYFFqhBjERYOn97tCureFgYH1E="
    url:
      css: "https://cdn.jsdelivr.net/npm/swiper@{version}/swiper-bundle.min.css"
      js: "https://cdn.jsdelivr.net/npm/swiper@{version}/swiper-bundle.min.js"
    version: "11.0.5"
  vega:
    integrity:
      js: "sha256-Yot/cfgMMMpFwkp/5azR20Tfkt24PFqQ6IQS+80HIZs="
      js_map: "sha256-z3QKkqNgeMdVvE9QwsVbsUzqrOYjXPRA+Wz0dg2S4x8="
    url:
      js: "https://cdn.jsdelivr.net/npm/vega@{version}/build/vega.min.js"
      js_map: "https://cdn.jsdelivr.net/npm/vega@{version}/build/vega.min.js.map"
    version: "5.27.0"
  vega-embed:
    integrity:
      js: "sha256-FPCJ9JYCC9AZSpvC/t/wHBX7ybueZhIqOMjpWqfl3DU="
    url:
      js: "https://cdn.jsdelivr.net/npm/vega-embed@{version}/build/vega-embed.min.js"
    version: "6.24.0"
  vega-lite:
    integrity:
      js: "sha256-TvBvIS5jUN4BSy009usRjKzLe2EoqXqaS5wCgNnau5E="
    url:
      js: "https://cdn.jsdelivr.net/npm/vega-lite@{version}/build/vega-lite.min.js"
    version: "5.16.3"
